{{- if and .Values.fortifyConnectServer.enabled .Values.fortifyConnectServer.networkPolicyEnabled }}
# Isolate fortify-connect server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dast-fortifyconnectserver.fullname" . }}
  labels:
    component: fortifyconnectserver
    {{- include "dast.labels" . | nindent 4 }}
spec:
  {{- if .Values.fortifyConnectServer.localPortForwardingEnabled }}
  egress:
    - to:
      - podSelector:
          matchLabels:
            component: api
            {{- include "dast.selectorLabels" . | nindent 12 }}
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: lim
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
    - ports:
      - port: 53
        protocol: UDP
      to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
  {{- end }}
  ingress:
    - ports:
      - port: 2022
        protocol: TCP
    - from:
      - podSelector:
          matchLabels:
            component: api
            {{- include "dast.selectorLabels" . | nindent 12 }}
    - from:
      - podSelector:
          matchLabels:
            component: scanner
            {{- include "dast.selectorLabels" . | nindent 12 }}
  podSelector:
    matchLabels:
      component: fortifyconnectserver
      {{- include "dast.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
{{- end }}