{{- if not .Values.secretName }}
{{- $dbProvider := default "SQLServer" .Values.configuration.databaseSettings.databaseProvider  }}
{{- $dbServer := default "server" .Values.configuration.databaseSettings.server  }}
{{- $dbName := default "dast" .Values.configuration.databaseSettings.database }}
{{- $dbUser := default "user" .Values.configuration.databaseSettings.standardDatabaseAccount.username }}
{{- $dbPwd := default "password" .Values.configuration.databaseSettings.standardDatabaseAccount.password }}
{{- $dbAdditionalProps := default "" .Values.configuration.databaseSettings.standardDatabaseAccount.additionalConnectionProperties }}
{{- $dbConnStr := "" }}
{{- if has $dbProvider (list "SQLServer" "AzureSQLServer" "AmazonRdsSQLServer") }}
{{- $dbConnStr = printf "Server=%s; Database=%s; User Id=%s; Password=%s;" $dbServer $dbName $dbUser $dbPwd }}
{{- else if has $dbProvider (list "PostgreSQL" "AzurePostgreSQL" "AmazonRdsPostgreSQL") -}}
{{- $dbConnStr = printf "Host=%s; Database=%s; User Id=%s; Password=%s;" $dbServer $dbName $dbUser $dbPwd }}
{{- else }}
{{- fail "Invalid value at \".Values.configuration.databaseSettings.databaseProvider\". Refer to \"values.yaml\" for all the options." }}
{{- end }}
{{- if $dbAdditionalProps }}
# TODO Support additionalProps starting with ; and without
{{- $dbConnStr = printf "%s %s" $dbConnStr $dbAdditionalProps }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  labels:
    component: secret
    {{- include "dast.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-20"
type: Opaque
data:
  db-connection-string: {{ $dbConnStr | b64enc | quote }}
  service-token: {{ .Values.configuration.serviceToken | toString | b64enc | quote }}
  wise-auth-token: {{ .Values.wise.authenticationToken | toString | b64enc | quote }}
  two-factor-auth-master-token: {{ .Values.twofactorauth.masterToken | toString | b64enc | quote }}
  appsettings.yaml: {{ .Values.configuration | toYaml | toString |  b64enc | quote }}
  {{- if .Values.fortifyConnectServer.enabled }}
  fortify-connect-public-key-contents: {{ .Values.configuration.fortifyConnectServerSettings.publicKeyContents | b64enc | quote }}
  {{- end }}
{{- end }}