{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lim-secret.fullname" . }}
  labels:
    component: secret
    {{- include "lim.labels" . | nindent 4 }}
type: Opaque
data:
  lim-admin-password: {{ include "secrets.passwords.manage" (dict "secret" (include "lim-secret.fullname" .) "key" "lim-admin-password" "providedPassword" .Values.defaultAdministrator.password "length" 16 "context" $ ) }}
  lim-jwt-security-key: {{ include "secrets.passwords.manage" (dict "secret" (include "lim-secret.fullname" .) "key" "lim-jwt-security-key" "providedPassword" .Values.jwtSecurityKey "length" 48 "context" $ ) }}
  {{- if .Values.proxy.password }}
  lim-proxy-password: {{ .Values.proxy.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.serverCertificate.enabled }}
  lim-server-certificate: {{ .Values.serverCertificate.certificateBase64 | quote }}
  lim-server-certificate-password: {{ if .Values.serverCertificate.password }}{{ .Values.serverCertificate.password | b64enc | quote }}{{ else }}""{{ end }}
  {{- end }}
  {{- if not .Values.signingCertificate.autoGenerate }}
  lim-signing-certificate: {{ .Values.signingCertificate.certificateBase64 | quote }}
  lim-signing-certificate-password: {{ if .Values.signingCertificate.password }}{{ .Values.signingCertificate.password | b64enc | quote }}{{ else }}""{{ end }}
  {{- end }}
{{- end }}