apiVersion: v1
kind: Service
metadata:
  name: {{ include "lim.fullname" . }}
  labels:
    {{- include "lim.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.serverCertificate.enabled }}
    - port: {{ .Values.service.portTls }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "lim.selectorLabels" . | nindent 4 }}
